apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- base/argo-cd-ui-ingress.yaml
- github.com/argoproj/argo-cd//manifests/ha/install.yaml?ref=v2.7.1

patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
- overlays/production/argocd-server-service.yaml
